'use strict';
Object.defineProperty(exports, "__esModule", { value: true });
var Phrase;
(function (Phrase) {
    function create(type, start, end, children) {
        return {
            phraseType: type,
            start: start,
            end: end,
            children: children
        };
    }
    Phrase.create = create;
    function createParseError(start, end, children, unexpected, expected) {
        return {
            phraseType: 61,
            start: start,
            end: end,
            children: children,
            unexpected: unexpected,
            expected: expected
        };
    }
    Phrase.createParseError = createParseError;
})(Phrase = exports.Phrase || (exports.Phrase = {}));
function phraseTypeToString(type) {
    switch (type) {
        case 0:
            return 'Unknown';
        case 1:
            return 'AdditiveExpression';
        case 2:
            return 'AnonymousClassDeclaration';
        case 3:
            return 'AnonymousClassDeclarationHeader';
        case 4:
            return 'AnonymousFunctionCreationExpression';
        case 5:
            return 'AnonymousFunctionHeader';
        case 6:
            return 'AnonymousFunctionUseClause';
        case 7:
            return 'AnonymousFunctionUseVariable';
        case 8:
            return 'ArgumentExpressionList';
        case 9:
            return 'ArrayCreationExpression';
        case 10:
            return 'ArrayElement';
        case 11:
            return 'ArrayInitialiserList';
        case 12:
            return 'ArrayKey';
        case 13:
            return 'ArrayValue';
        case 14:
            return 'BitwiseExpression';
        case 15:
            return 'BreakStatement';
        case 16:
            return 'ByRefAssignmentExpression';
        case 17:
            return 'CaseStatement';
        case 18:
            return 'CaseStatementList';
        case 19:
            return 'CastExpression';
        case 20:
            return 'CatchClause';
        case 21:
            return 'CatchClauseList';
        case 22:
            return 'CatchNameList';
        case 23:
            return 'ClassBaseClause';
        case 24:
            return 'ClassConstantAccessExpression';
        case 25:
            return 'ClassConstDeclaration';
        case 26:
            return 'ClassConstElement';
        case 27:
            return 'ClassConstElementList';
        case 28:
            return 'ClassDeclaration';
        case 29:
            return 'ClassDeclarationBody';
        case 30:
            return 'ClassDeclarationHeader';
        case 31:
            return 'ClassInterfaceClause';
        case 32:
            return 'ClassMemberDeclarationList';
        case 33:
            return 'ClassModifiers';
        case 34:
            return 'ClassTypeDesignator';
        case 35:
            return 'CloneExpression';
        case 36:
            return 'ClosureUseList';
        case 37:
            return 'CoalesceExpression';
        case 38:
            return 'CompoundAssignmentExpression';
        case 39:
            return 'CompoundStatement';
        case 40:
            return 'TernaryExpression';
        case 41:
            return 'ConstantAccessExpression';
        case 42:
            return 'ConstDeclaration';
        case 43:
            return 'ConstElement';
        case 44:
            return 'ConstElementList';
        case 45:
            return 'ContinueStatement';
        case 46:
            return 'DeclareDirective';
        case 47:
            return 'DeclareStatement';
        case 48:
            return 'DefaultStatement';
        case 50:
            return 'DoStatement';
        case 51:
            return 'DoubleQuotedStringLiteral';
        case 52:
            return 'EchoIntrinsic';
        case 53:
            return 'ElseClause';
        case 54:
            return 'ElseIfClause';
        case 55:
            return 'ElseIfClauseList';
        case 56:
            return 'EmptyIntrinsic';
        case 57:
            return 'EncapsulatedExpression';
        case 58:
            return 'EncapsulatedVariable';
        case 59:
            return 'EncapsulatedVariableList';
        case 60:
            return 'EqualityExpression';
        case 61:
            return 'Error';
        case 62:
            return 'ErrorClassMemberDeclaration';
        case 63:
            return 'ErrorClassTypeDesignatorAtom';
        case 64:
            return 'ErrorControlExpression';
        case 65:
            return 'ErrorExpression';
        case 66:
            return 'ErrorScopedAccessExpression';
        case 67:
            return 'ErrorTraitAdaptation';
        case 68:
            return 'ErrorVariable';
        case 69:
            return 'ErrorVariableAtom';
        case 70:
            return 'EvalIntrinsic';
        case 71:
            return 'ExitIntrinsic';
        case 72:
            return 'ExponentiationExpression';
        case 73:
            return 'ExpressionList';
        case 74:
            return 'ExpressionStatement';
        case 75:
            return 'FinallyClause';
        case 76:
            return 'ForControl';
        case 77:
            return 'ForeachCollection';
        case 78:
            return 'ForeachKey';
        case 79:
            return 'ForeachStatement';
        case 80:
            return 'ForeachValue';
        case 81:
            return 'ForEndOfLoop';
        case 82:
            return 'ForExpressionGroup';
        case 83:
            return 'ForInitialiser';
        case 84:
            return 'ForStatement';
        case 85:
            return 'FullyQualifiedName';
        case 86:
            return 'FunctionCallExpression';
        case 87:
            return 'FunctionDeclaration';
        case 89:
            return 'FunctionDeclarationHeader';
        case 88:
            return 'FunctionDeclarationBody';
        case 90:
            return 'FunctionStaticDeclaration';
        case 91:
            return 'FunctionStaticInitialiser';
        case 92:
            return 'GlobalDeclaration';
        case 93:
            return 'GotoStatement';
        case 94:
            return 'HaltCompilerStatement';
        case 95:
            return 'HeredocStringLiteral';
        case 96:
            return 'Identifier';
        case 97:
            return 'IfStatement';
        case 98:
            return 'IncludeExpression';
        case 99:
            return 'IncludeOnceExpression';
        case 100:
            return 'InlineText';
        case 101:
            return 'InstanceOfExpression';
        case 102:
            return 'InstanceofTypeDesignator';
        case 103:
            return 'InterfaceBaseClause';
        case 104:
            return 'InterfaceDeclaration';
        case 105:
            return 'InterfaceDeclarationBody';
        case 106:
            return 'InterfaceDeclarationHeader';
        case 107:
            return 'InterfaceMemberDeclarationList';
        case 108:
            return 'IssetIntrinsic';
        case 109:
            return 'ListIntrinsic';
        case 110:
            return 'LogicalExpression';
        case 111:
            return 'MemberModifierList';
        case 112:
            return 'MemberName';
        case 113:
            return 'MethodCallExpression';
        case 114:
            return 'MethodDeclaration';
        case 115:
            return 'MethodDeclarationBody';
        case 116:
            return 'MethodDeclarationHeader';
        case 117:
            return 'MethodReference';
        case 118:
            return 'MultiplicativeExpression';
        case 119:
            return 'NamedLabelStatement';
        case 120:
            return 'NamespaceAliasingClause';
        case 121:
            return 'NamespaceDefinition';
        case 124:
            return 'NamespaceName';
        case 125:
            return 'NamespaceUseClause';
        case 126:
            return 'NamespaceUseClauseList';
        case 127:
            return 'NamespaceUseDeclaration';
        case 128:
            return 'NamespaceUseGroupClause';
        case 129:
            return 'NamespaceUseGroupClauseList';
        case 130:
            return 'NullStatement';
        case 131:
            return 'ObjectCreationExpression';
        case 132:
            return 'ParameterDeclaration';
        case 133:
            return 'ParameterDeclarationList';
        case 134:
            return 'PostfixDecrementExpression';
        case 135:
            return 'PostfixIncrementExpression';
        case 136:
            return 'PrefixDecrementExpression';
        case 137:
            return 'PrefixIncrementExpression';
        case 138:
            return 'PrintIntrinsic';
        case 139:
            return 'PropertyAccessExpression';
        case 140:
            return 'PropertyDeclaration';
        case 141:
            return 'PropertyElement';
        case 142:
            return 'PropertyElementList';
        case 143:
            return 'PropertyInitialiser';
        case 144:
            return 'QualifiedName';
        case 145:
            return 'QualifiedNameList';
        case 146:
            return 'RelationalExpression';
        case 147:
            return 'RelativeQualifiedName';
        case 148:
            return 'RelativeScope';
        case 149:
            return 'RequireExpression';
        case 150:
            return 'RequireOnceExpression';
        case 151:
            return 'ReturnStatement';
        case 152:
            return 'ReturnType';
        case 153:
            return 'ScopedCallExpression';
        case 154:
            return 'ScopedMemberName';
        case 155:
            return 'ScopedPropertyAccessExpression';
        case 156:
            return 'ShellCommandExpression';
        case 157:
            return 'ShiftExpression';
        case 158:
            return 'SimpleAssignmentExpression';
        case 159:
            return 'SimpleVariable';
        case 160:
            return 'StatementList';
        case 161:
            return 'StaticVariableDeclaration';
        case 162:
            return 'StaticVariableDeclarationList';
        case 163:
            return 'SubscriptExpression';
        case 164:
            return 'SwitchStatement';
        case 165:
            return 'ThrowStatement';
        case 166:
            return 'TraitAdaptationList';
        case 167:
            return 'TraitAlias';
        case 168:
            return 'TraitDeclaration';
        case 169:
            return 'TraitDeclarationBody';
        case 170:
            return 'TraitDeclarationHeader';
        case 171:
            return 'TraitMemberDeclarationList';
        case 172:
            return 'TraitPrecedence';
        case 173:
            return 'TraitUseClause';
        case 174:
            return 'TraitUseSpecification';
        case 175:
            return 'TryStatement';
        case 176:
            return 'TypeDeclaration';
        case 177:
            return 'UnaryOpExpression';
        case 178:
            return 'UnsetIntrinsic';
        case 179:
            return 'VariableList';
        case 180:
            return 'VariableNameList';
        case 181:
            return 'VariadicUnpacking';
        case 182:
            return 'WhileStatement';
        case 183:
            return 'YieldExpression';
        case 184:
            return 'YieldFromExpression';
        case 49:
            return 'DocBlock';
        default:
            return '';
    }
}
exports.phraseTypeToString = phraseTypeToString;
